#!/usr/bin/env bash

# Current default versions for all relevant packages

# TPSL (10 items)

GLM_VERSION=0.9.9.6
HYPRE_VERSION=2.18.0
MATIO_VERSION=1.5.18
METIS_VERSION=5.1.0
MUMPS_VERSION=5.2.1
PARMETIS_VERSION=4.0.3
SCOTCH_VERSION=6.0.10
SUPERLU_VERSION=5.2.1
SUPERLUDIST_VERSION=6.1.1
SUNDIALS_VERSION=4.1.0

# Others (5 items)

PETSC_VERSION=3.13.3
SLEPC_VERSION=
ADIOS_VERSION=
BOOST_VERSION=
TRILINOS_VERSION=
