#!/usr/bin/env bash

set -e

script="$(readlink -fm "$0")"
script_dir="$(dirname "${script}")"
script_root="$(dirname "${script%/*/*}")"

source ${script_root}/pkgconfig-lib.sh
source ${script_root}/versions.sh
source ${script_root}/command_line.sh

xthi_src_location=/work/z19/z19/kevin/xthi/src
XTHI_VERSION="1.2"

function main {

    # Overall prefix must be supplied by command line

    local install_root=${install_root_utils}/xthi/${XTHI_VERSION}

    #${build_cce} && xthiBuildCray ${install_root}
    #${build_gnu} && xthiBuildGnu  ${install_root}
    #${build_amd} && xthiBuildAocc ${install_root}

    xthiInstallModuleFileLua
    xthiInstallationTest
}

function xthiBuildAocc {

    local install_root=${1}

    # Restore relevant PE/Compiler

    module load PrgEnv-aocc
    module load aocc/${PE_AOCC_AOCC_VERSION}
    module list

    amd_version=$(moduleToCompilerMajorMinor)
    amd_root=${install_root}/AOCC
    amd_prefix=${amd_root}/${amd_version}

    xthiBuild ${amd_prefix}
}

function xthiBuildCray {

    local install_root=${1}

    module load PrgEnv-cray
    module load cce/${PE_CRAY_CCE_VERSION}
    module list

    cray_version=$(moduleToCompilerMajorMinor)
    cray_root=${install_root}/CRAYCLANG
    cray_prefix=${cray_root}/${cray_version}

    xthiBuild ${cray_prefix}
}

function xthiBuildGnu {    

    local install_root=${1}

    module load PrgEnv-gnu
    module load gcc/${PE_GNU_GCC_VERSION}
    module list

    gnu_version=$(moduleToCompilerMajorMinor)
    gnu_root=${install_root}/GNU
    gnu_prefix=${gnu_root}/${gnu_version}

    xthiBuild ${gnu_prefix}
}

function xthiBuild {

    local prefix=${1}
    
    # Build OpenMP first and then MPI (prevents clobbering serial version)
    xthiClean
    xthiBuildMPIOpenMP ${prefix}

    xthiPackageConfigFiles ${prefix}

    # Remove shared objects from package config stage
    rm ${prefix}/lib/*.so

}

function xthiClean {

    make -C ${xthi_src_location} clean

}

function xthiBuildMPIOpenMP {

    # libxthi.a / .so generated by build

    local prefix=${1}

    local pe=$(peEnvLower)

    make -C ${xthi_src_location} xthi
    make -C ${xthi_src_location} xthi_mp
    PREFIX=${prefix} make -C ${xthi_src_location} install

    local name_mpi_mp=libxthi_${pe}_mpi_mp

    mv ${prefix}/lib/libxthi_mpi_mp.a  ${prefix}/lib/${name_mpi_mp}.a
    mv ${prefix}/lib/libxthi_mpi_mp.so ${prefix}/lib/${name_mpi_mp}.so

    local name_mpi=libxthi_${pe}_mpi

    mv ${prefix}/lib/libxthi_mpi.a  ${prefix}/lib/${name_mpi}.a
    mv ${prefix}/lib/libxthi_mpi.so ${prefix}/lib/${name_mpi}.so
}

function xthiPackageConfigFiles {

    # Here we declare the necessary information required to generate
    # pkgconfig files
    
    local prefix=${1}
    local prgEnv=$(peEnvLower)
    
    declare -A pcmap
    pcmap[name]="xthi"
    pcmap[version]=${XTHI_VERSION}
    pcmap[description]="xthi library for ${prgEnv} compiler"
    pcmap[has_openmp]=1

    pcmap[requires]="xthi_${prgEnv}_mpi"

    pcRefactorPackageConfigFiles ${prefix} pcmap
    pcFileWriteOverallPackageFile "${prefix}/lib/pkgconfig/xthi.pc" pcmap
}

function xthiInstallModuleFileLua {

    local module_preamble=${script_dir}/module_preamble.lua
    local module_boilerplate=${script_dir}/module_boilerplate.lua

    # Destination
    local module_dir=$(moduleInstallDirectoryUtils)

    if [[ ! -d ${module_dir}/xthi ]]; then
        mkdir ${module_dir}/xthi
    fi

    local module_file=${module_dir}/xthi/${XTHI_VERSION}.lua

    # Copy add update the template

    cat ${module_preamble}     > ${module_file}
    cat ${module_boilerplate} >> ${module_file}

    module use ${module_dir}
    module load xthi/${XTHI_VERSION}

    cc --cray-print-opts

    module unload xthi
    module unuse ${module_dir}
}

function xthiInstallationTest {

    ${test_cce} && xthiTest PrgEnv-cray
    ${test_gnu} && xthiTest PrgEnv-gnu
    ${test_amd} && xthiTest PrgEnv-aocc

    printf "Completed xthi installation successfully\n"
}

function xthiTest {

    local prgenv="${1}"
    local module_use=$(moduleInstallDirectoryUtils)

    printf "xthi test for %s\n" "${prgenv}"

    module load ${prgenv}
    module use ${module_use}

    module load xthi/${XTHI_VERSION}
    printf "XTHI_DIR: %s\n" "${XTHI_DIR}"

    slurmAllocRun "srun -n 3 xthi_mpi"


    slurmAllocRun "srun -n 2 --distribution=block:block --hint=nomultithread xthi_mpi_mp"
    module unload xthi
}

main
