#!/usr/bin/env bash

set -e

script="$(readlink -fm "$0")"
script_dir="$(dirname "${script}")"
script_root="$(dirname "${script%/*/*}")"

source ${script_root}/pkgconfig-lib.sh
source ${script_root}/versions.sh
source ${script_root}/command_line.sh

function main {

    # Overall prefix must be supplied by command line

    local install_root=${prefix}/libs/parmetis/${PARMETIS_VERSION}

    parmetisBuildCray ${install_root}
    parmetisBuildGnu  ${install_root}
    parmetisBuildAocc ${install_root}

    parmetisInstallModuleFile
    parmetisInstallationTest
}

function parmetisBuildAocc {

    local install_root=${1}

    # Restore relevant PE/Compiler
    module restore $(moduleCollection PrgEnv-aocc)
    module swap aocc aocc/${PE_AOCC_AOCC_VERSION}

    moduleUseLibs
    module load metis/${METIS_VERSION}
    module list

    amd_version=$(moduleToCompilerMajorMinor)
    amd_root=${install_root}/AOCC
    amd_prefix=${amd_root}/${amd_version}

    parmetisBuild ${amd_prefix}
}

function parmetisBuildCray {

    local install_root=${1}

    module restore $(moduleCollection PrgEnv-cray)
    module swap cce cce/${PE_CRAY_CCE_VERSION}

    moduleUseLibs
    module load metis/${METIS_VERSION}
    module list

    cray_version=$(moduleToCompilerMajorMinor)
    cray_root=${install_root}/CRAYCLANG
    cray_prefix=${cray_root}/${cray_version}

    parmetisBuild ${cray_prefix}
}

function parmetisBuildGnu {    

    local install_root=${1}

    module restore $(moduleCollection PrgEnv-gnu)
    module swap gcc gcc/${PE_GNU_GCC_VERSION}

    moduleUseLibs
    module load metis/${METIS_VERSION}
    module list

    gnu_version=$(moduleToCompilerMajorMinor)
    gnu_root=${install_root}/GNU
    gnu_prefix=${gnu_root}/${gnu_version}

    parmetisBuild ${gnu_prefix}
}

function parmetisBuild {

    local prefix=${1}
    
    # Build OpenMP first and then MPI (prevents clobbering serial version)
    parmetisClean
    parmetisBuildMPIOpenMP ${prefix}
    parmetisClean
    parmetisBuildMPI ${prefix}

    parmetisPackageConfigFiles ${prefix}

    # Remove shared objects from package config stage
    rm ${prefix}/lib/*.so

}

function parmetisClean {

    rm -rf parmetis-${PARMETIS_VERSION}

}

function parmetisBuildMPI {

    # libparmetis.a is generated

    local prefix=${1}

    ./sh/tpsl/parmetis.sh --jobs=16 --prefix=${prefix} --modules --version=${PARMETIS_VERSION}

    local pe=$(peEnvLower)
    local newname=libparmetis_${pe}_mpi.a

    mv ${prefix}/lib/libparmetis.a ${prefix}/lib/${newname}
    ccSharedFromStatic ${prefix}/lib parmetis_${pe}_mpi
}

function parmetisBuildMPIOpenMP {

    # libparmetis.a is generated by build

    local prefix=${1}

    local pe=$(peEnvLower)
    local newname=libparmetis_${pe}_mpi_mp.a

    ./sh/tpsl/parmetis.sh --jobs=16 --prefix=${prefix} --openmp --modules \
			  --version=${PARMETIS_VERSION}

    mv ${prefix}/lib/libparmetis.a ${prefix}/lib/${newname}
    ccSharedFromStatic ${prefix}/lib parmetis_${pe}_mpi_mp
}

function parmetisPackageConfigFiles {

    # Here we declare the necessary information required to generate
    # pkgconfig files
    
    local prefix=${1}
    local prgEnv=$(peEnvLower)
    
    declare -A pcmap
    pcmap[name]="parmetis"
    pcmap[version]=${PARMETIS_VERSION}
    pcmap[description]="parmetis library for ${prgEnv} compiler"
    pcmap[has_openmp]=1

    pcmap[requires]="parmetis_${prgEnv}_mpi"

    pcRefactorPackageConfigFiles ${prefix} pcmap
    pcFileWriteOverallPackageFile "${prefix}/lib/pkgconfig/parmetis.pc" pcmap
}

function parmetisInstallModuleFile {

    local module_template=${script_dir}/modulefile.tcl

    # Destination
    local module_dir=$(moduleInstallDirectory)
    local time_stamp=$(date)
    
    if [[ ! -d ${module_dir}/parmetis ]]; then
	mkdir ${module_dir}/parmetis
    fi

    local module_file=${module_dir}/parmetis/${PARMETIS_VERSION}

    # Copy add update the template
    cp ${module_template} ${module_file}
    sed -i "s%TEMPLATE_INSTALL_ROOT%${prefix}%" ${module_file}
    sed -i "s%TEMPLATE_PARMETIS_VERSION%${PARMETIS_VERSION}%" ${module_file}
    sed -i "s%TEMPLATE_METIS_VERSION%${METIS_VERSION}%" ${module_file}
    sed -i "s%TEMPLATE_TIMESTAMP%${time_stamp}%" ${module_file}
    
    # Ensure this has worked
    module use ${module_dir}
    module load parmetis/${PARMETIS_VERSION}
    module unload parmetis

}

function parmetisInstallationTest {

    parmetisTest PrgEnv-cray
    parmetisTest PrgEnv-gnu
    parmetisTest PrgEnv-aocc

    printf "Completed parmetis installation successfully\n"
}

function parmetisTest {

    local prgenv="${1}"
    local module_use=$(moduleInstallDirectory)

    printf "Parmetis test for %s\n" "${prgenv}"
    module restore $(moduleCollection ${prgenv})
    module use ${module_use}

    module load parmetis/${PARMETIS_VERSION}
    printf "PARMETIS_DIR: %s\n" "${PARMETIS_DIR}"

    cd parmetis-${PARMETIS_VERSION}

    cp ${script_dir}/parmetis-install.c parmetis-install.c
    cc parmetis-install.c

    slurmAllocRun "srun -n 3 ./a.out"

    cd -
}

main
