#!/usr/bin/env bash

set -e

script="$(readlink -fm "$0")"
script_dir="$(dirname "${script}")"
script_root="$(dirname "${script%/*/*}")"

source ${script_root}/pkgconfig-lib.sh
source ${script_root}/versions.sh
source ${script_root}/command_line.sh

function main {

    # Overall prefix must be supplied by command line

    local install_root=${prefix}/libs/arpack-ng/${ARPACK_VERSION}

    arpackBuildAocc ${install_root}
    arpackBuildCray ${install_root}
    arpackBuildGnu  ${install_root}
    
    arpackInstallModuleFile
    arpackInstallationTest ${install_root}

    printf "Arpack nstallation test completed successfully\n"
}

function arpackBuildAocc {

    local install_root=${1}
    
    # buildVersion AOCC 2.1
    module -s restore PrgEnv-aocc
    module list

    amd_version=2.1
    amd_root=${install_root}/AOCC
    amd_prefix=${amd_root}/${amd_version}

    arpackBuild ${amd_prefix}
}

function arpackBuildCray {

    local install_root=${1}

    # buildVersion CRAYCLANG 10.0
    module -s restore PrgEnv-cray
    module list

    cray_version=10.0
    cray_root=${install_root}/CRAYCLANG
    cray_prefix=${cray_root}/${cray_version}

    arpackBuild ${cray_prefix}
}

function arpackBuildGnu {    

    local install_root=${1}

    # buildVersion GNU 9.3
    module -s restore PrgEnv-gnu
    module swap gcc gcc/9.3.0
    module list

    gnu_version=9.3
    gnu_root=${install_root}/GNU
    gnu_prefix=${gnu_root}/${gnu_version}

    arpackBuild ${gnu_prefix}
}

function arpackBuild {

    local prefix=${1}
    
    # The single build produces both serial and MPI versions.

    arpackClean
    arpackBuildMPI ${prefix}

    # Remove pre-supplied arpack.ps parpack.pc
    rm ${prefix}/lib/pkgconfig/arpack.pc
    rm ${prefix}/lib/pkgconfig/parpack.pc

    arpackPackageConfigFiles ${prefix}

    # At the moment we are removing any shared objects
    rm ${prefix}/lib/lib*.so
}

function arpackClean {

    rm -rf arpack-ng-${ARPACK_VERSION}

}

function arpackBuildMPI {

    # The following libraries are generated by the build:
    # arpack.a parpack.a
    # (serial and parallel versions; there are no common symbols).

    local prefix=${1}

    ./sh/arpack-ng.sh --jobs=16 --prefix=${prefix} --version=${ARPACK_VERSION}

    local pe=$(peEnvLower)

    cd ${prefix}/lib

    mv libarpack.a libarpack_${pe}.a
    ln -s libarpack_${pe}.a libarpack.a
    ccSharedFromStatic ${prefix}/lib arpack_${pe}

    mv libparpack.a libparpack_${pe}_mpi.a
    ln -s libparpack_${pe}_mpi.a libparpack.a
    ccSharedFromStatic ${prefix}/lib parpack_${pe}_mpi

    cd -
}

function arpackPackageConfigFiles {

    # Here we declare the necessary information required to generate
    # pkgconfig files

    local prefix=${1}
    local prgEnv=$(peEnvLower)
    local ext="${prgEnv}"
    local extmpi="${prgEnv}_mpi"
    
    declare -A pcmap
    pcmap[name]="arpack-ng"
    pcmap[version]="${ARPACK_VERSION}"
    pcmap[description]="Arpack-NG library for ${prgEnv} compiler"
    pcmap[has_openmp]=0

    pcmap[requires]="parpack_${extmpi} arpack_${ext}"

    pcRefactorPackageConfigFiles ${prefix} pcmap
    pcFileWriteOverallPackageFile "${prefix}/lib/pkgconfig/arpack-ng.pc" pcmap
}

function arpackInstallModuleFile {

    local module_template=${script_dir}/modulefile.tcl

    # Destination
    local module_dir=$(moduleInstallDirectory)
    local time_stamp=$(date)

    if [[ ! -d ${module_dir}/arpack-ng ]]; then
	mkdir ${module_dir}/arpack-ng
    fi

    local module_file=${module_dir}/arpack-ng/${ARPACK_VERSION}

    # Copy add update the template
    cp ${module_template} ${module_file}
    sed -i "s%TEMPLATE_INSTALL_ROOT%${prefix}%" ${module_file}
    sed -i "s%TEMPLATE_ARPACK_VERSION%${ARPACK_VERSION}%" ${module_file}
    sed -i "s%TEMPLATE_TIMESTAMP%${time_stamp}%" ${module_file}

    # Ensure this has worked
    module use ${module_dir}
    module load arpack-ng/${ARPACK_VERSION}
    module unload arpack-ng

}

function arpackInstallationTest {

    arpackTest PrgEnv-cray
    arpackTest PrgEnv-gnu
    arpackTest PrgEnv-aocc

}

function arpackTest {

    local prgenv=${1}
    local module_use=$(moduleInstallDirectory)
    local version="${ARPACK_VERSION}"

    printf "Arpack-NG test for %s\n" "${prgenv}"
    module -s restore ${prgenv}
    module use ${module_use}

    module load arpack-ng/${version}
    printf "ARPACK_DIR: %s\n" "${ARPACK_DIR}"

    printf "Please provide installation test\n"
}

main
